PROJECT_NAME: medpointSystemBE
PROJECT_ID: gercqdrpnwbungwtmigf
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_bbfa1bea2b3b8da7309172ae66abb79fe7a88b7e
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlcmNxZHJwbndidW5nd3RtaWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3ODA3MDAsImV4cCI6MjA0ODM1NjcwMH0.opVZ3eb614DzBSWAfVY1ZbQQvLtgvylaJBR7if84hQI
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlcmNxZHJwbndidW5nd3RtaWdmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjc4MDcwMCwiZXhwIjoyMDQ4MzU2NzAwfQ.HGEW2RD4EKLKkTFw6zZ6I0Vr5IPZfoQ0Jjf1K58JmV8

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://gercqdrpnwbungwtmigf.supabase.co

SERVER_HOST: 127.0.01
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
