name: Deploy to Vercel

on:
  push:
    tags:
      - 'v*' # Trigger hanya untuk tag baru dengan format seperti v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 3: Deploy ke Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token $VERCEL_TOKEN
